AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
ENCODER_ENABLE = no
DIP_SWITCH_ENABLE = no

STENO_ENABLE = yes
STENO_PROTOCOL = geminipr
VIRSTER_ENABLE = no