#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#define COMBO_TERM 40
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_MUST_HOLD_PER_COMBO

#define RGBLIGHT_LAYERS

#define MIDI_ADVANCED
