#ifdef AUDIO_ENABLE
#define DVORAK_AMERICAN E__NOTE(_F4), Q__NOTE(_A4), E__NOTE(_C5), ED_NOTE(_D5), S__NOTE(_F5), Q__NOTE(_D5), ED_NOTE(_C5), S__NOTE(_A4), E__NOTE(_F4), S__NOTE(_G4), S__NOTE(_A4), H__NOTE(_C5)
//#define PLOVER_JVOICE E__NOTE(_F4), SD_NOTE(_AS4), T__NOTE(_REST), SD_NOTE(_AS4), T__NOTE(_REST), SD_NOTE(_AS4), T__NOTE(_REST), E__NOTE(_AS4), E__NOTE(_C5), SD_NOTE(_F5), T__NOTE(_REST), E__NOTE(_F5)
#define PLOVER_JVOICE E__NOTE(_F4), E__NOTE(_AS4), E__NOTE(_C5), E__NOTE(_F5)
#define NUMPAD_SCALE S__NOTE(_C4), S__NOTE(_D4), S__NOTE(_E4), S__NOTE(_F4), S__NOTE(_G4), S__NOTE(_A4), S__NOTE(_B4), S__NOTE(_C5), S__NOTE(_D5)
#define MIDI_SIB6 QD_NOTE(_G6), E__NOTE(_A6), H__NOTE(_F6), QD_NOTE(_A6), E__NOTE(_B6), QD_NOTE(_G6)
#endif
